CREATE TABLE users (
    id UUID PRIMARY KEY,
    firebase_uid VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    photo_url TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE avatars (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    name VARCHAR(255),
    picture TEXT,
    story TEXT,
    level INTEGER DEFAULT 1,
    experience INTEGER DEFAULT 0,
    total_experience INTEGER DEFAULT 0,
    next_level_experience INTEGER,
    stamina INTEGER DEFAULT 100,
    life INTEGER DEFAULT 100,
    money DECIMAL(19, 2) DEFAULT 0.0,
    available_points INTEGER DEFAULT 0,
    intelligence INTEGER DEFAULT 0,
    charisma INTEGER DEFAULT 0,
    strength INTEGER DEFAULT 0,
    stealth INTEGER DEFAULT 0,
    temporary_strength INTEGER DEFAULT 0,
    temporary_intelligence INTEGER DEFAULT 0,
    temporary_charisma INTEGER DEFAULT 0,
    temporary_stealth INTEGER DEFAULT 0,
    status_cooldown TIMESTAMP,
    hacking INTEGER DEFAULT 0,
    work INTEGER DEFAULT 0,
    timeout TIMESTAMP,
    timeout_type VARCHAR(50),
    active BOOLEAN,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_avatars_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE actions (
    id UUID PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    stamina INTEGER,
    hp INTEGER,
    hp_variation DOUBLE PRECISION,
    money DECIMAL(19, 2),
    money_variation DOUBLE PRECISION,
    xp INTEGER,
    xp_variation DOUBLE PRECISION,
    required_strength INTEGER,
    required_intelligence INTEGER,
    required_charisma INTEGER,
    required_stealth INTEGER,
    can_be_arrested BOOLEAN,
    lost_hp_failure INTEGER,
    lost_hp_failure_variation DOUBLE PRECISION,
    text_file VARCHAR(255),
    action_image VARCHAR(255),
    failure_chance DOUBLE PRECISION,
    recommended_max_level INTEGER,
    temporary_strength INTEGER,
    temporary_intelligence INTEGER,
    temporary_charisma INTEGER,
    temporary_stealth INTEGER,
    action_cooldown TIMESTAMP,
    special_action VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

INSERT INTO users (id, firebase_uid, name, email, photo_url, created_at, updated_at)
VALUES ('00000000-0000-0000-0000-000000000000', 'mock-token-123', 'Mock User', 'mock-user@example.com', 'http://example.com/photo.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
